// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1wj2cNK6OAZaNBgSLQG7gicacOO2wNZc',
    appId: '1:1006306964273:web:994a2f12f16dc427023610',
    messagingSenderId: '1006306964273',
    projectId: 'bantu-aku-apps',
    authDomain: 'bantu-aku-apps.firebaseapp.com',
    storageBucket: 'bantu-aku-apps.firebasestorage.app',
    measurementId: 'G-Z2THJDNPP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA407KgUh1GyMOwzpnqUbdSkO-5rLWU_UU',
    appId: '1:1006306964273:android:dc33617fd15f79cf023610',
    messagingSenderId: '1006306964273',
    projectId: 'bantu-aku-apps',
    storageBucket: 'bantu-aku-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ5yoxxa3R6wVor3fawavUqBMIdkvDJWY',
    appId: '1:1006306964273:ios:5fb6129a8057153a023610',
    messagingSenderId: '1006306964273',
    projectId: 'bantu-aku-apps',
    storageBucket: 'bantu-aku-apps.firebasestorage.app',
    iosBundleId: 'com.bantuaku.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ5yoxxa3R6wVor3fawavUqBMIdkvDJWY',
    appId: '1:1006306964273:ios:c8105f1597c8bf06023610',
    messagingSenderId: '1006306964273',
    projectId: 'bantu-aku-apps',
    storageBucket: 'bantu-aku-apps.firebasestorage.app',
    iosBundleId: 'com.henry.flutterMvvmRiverpod',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1wj2cNK6OAZaNBgSLQG7gicacOO2wNZc',
    appId: '1:1006306964273:web:ec4d35f4abbe8f0e023610',
    messagingSenderId: '1006306964273',
    projectId: 'bantu-aku-apps',
    authDomain: 'bantu-aku-apps.firebaseapp.com',
    storageBucket: 'bantu-aku-apps.firebasestorage.app',
    measurementId: 'G-TYD33B6QQ5',
  );
}
